services:
  - type: web
    name: sistema-pqr
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.13
      - key: SECRET_KEY
        sync: false
      - key: ADMIN_PASS
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USE_TLS
        value: "true"
      - key: SMTP_USE_SSL
        value: "false"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: PQR_URL_BASE
        value: https://sistema-pqr.onrender.com
